DROP TABLE SALGRADE;
DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT (
    DEPTNO INT(2),
    DNAME VARCHAR(14),
    LOC VARCHAR(13),
    PRIMARY KEY (DEPTNO) 
);

CREATE TABLE EMP (
    EMPNO INT(4),
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR INT(4),
    HIREDATE DATE,
    SAL NUMERIC(7,2),
    COMM NUMERIC(7,2),
    DEPTNO INT(2),
    PRIMARY KEY (EMPNO),
    FOREIGN KEY (DEPTNO) references DEPT(DEPTNO),
    CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

CREATE TABLE SALGRADE ( 
    GRADE INT,
    LOSAL INT,
    HISAL INT 
);